apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Istio
metadata:
  name: istio
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  namespace: istio-system
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
